### ISSUE TITLE
Network plot - arrows

### ISSUE THREAD

**Issue by aleszib** [FATelarico/GUI-Generalised-Blockmodeling#13]
When using network package for plotting, the arrows are not displayed by default for the sample network, which is directed. 

When "Ovveride default arrow settings?" is checked (which is not by default), one can select to display the arrows, but this should be done by default for directed networks.

Also "Ovveride default arrow settings?" is misspelled.

**Comment by FATelarico** [comment]
The option is renamed, the typo corrected and the functioning fixed. A line explaining the 'default' settings is added.
![image](https://user-images.githubusercontent.com/100512813/161715074-8cf6ba95-7e5d-4682-9d05-b6b3fc3c69d1.png)

**Comment by FATelarico** [comment]
Now online in version [1.8.1 Rolling updates](https://github.com/FATelarico/GUI-Generalised-Blockmodeling/releases/tag/v.1.8.1)
