### ISSUE TITLE
The mean and error matrices should not be rounded to whole numbers (if they are not such already)

### ISSUE THREAD

**Issue by aleszib** [FATelarico/GUI-Generalised-Blockmodeling#16]
The mean and error matrices should not be rounded to whole numbers (if they are not such already). Also, it might be better to show (or perhaps in addition) the mean matrix using the plotMat function.

**Comment by FATelarico** [comment]
[Release notes v. 1.8.2](https://github.com/FATelarico/GUI-Generalised-Blockmodeling/releases/tag/v.1.8.2)
