### ISSUE TITLE
Correct the intial description

### ISSUE THREAD

**Issue by aleszib** [FATelarico/GUI-Generalised-Blockmodeling#17]
The initial description now among other things says:
"app allows also to perform a one-mode, generalised blockmodeling ~~using the "homogeinity" method"~~".

The strikethrough text should be removed, as other methods are now also implemented.

**Comment by FATelarico** [comment]
[Release notes v. 1.8.2](https://github.com/FATelarico/GUI-Generalised-Blockmodeling/releases/tag/v.1.8.2)
