### ISSUE TITLE
A bug due to density/average field

### ISSUE THREAD

**Issue by aleszib** [FATelarico/GUI-Generalised-Blockmodeling#19]
**Describe the bug**
Binary and valued blockmodeling do not work unless something is written in density/average field. 

**Expected behavior / Suggested solution**
It would makes sense to even show the density/average field only if density/average block type is selected. Also, I would position it differently, as were it now, it is not clear what is is for. I would put is under the field where block type are selected and even there it should be only shown if density/average is selected. Also, I would also give it a starting value. I would suggest this is the density of the network for density field and the average tie value (including 0 ties) for average field, if this is not too problematic to achieve.

**Comment by FATelarico** [comment]
Resolved by implementing the `hide()`/`show()` functions from the package `shinyjs()` (see v. [1.8.3](https://github.com/FATelarico/GUI-Generalised-Blockmodeling/releases/tag/v.1.8.3)).
