### ISSUE TITLE
Make the partitioned plot the default view in Network plot view if blockmodeling was already run

### ISSUE THREAD

**Issue by aleszib** [FATelarico/GUI-Generalised-Blockmodeling#20]
I would prefer that also in the Network Plot view, the partitioned plot would be the default if blockmodeling was already run, that is, whenever the partition is available.

This is an relatively optional request. While I think it would be beneficial, I don't know if it can be easily implemented.

I have already submitted/pushed a commit that makes the partitioned view the default in matrix view, but there the code was already adapted so that if the partition is not available, it shows the un-partitioned matrix.

**Comment by FATelarico** [comment]
The user cannot select the option to plot the partitions until the blockmodeling is run. Then, the partitioned network becomes the default option and the user can select the non-partitioned one. The user is informed by an on-text screen that he needs to run the blockmodeling before being able to see the option to plot the partitioned network.

The same mechanism was also extended to the plotting of matrices

(see v. [1.8.3](https://github.com/FATelarico/GUI-Generalised-Blockmodeling/releases/tag/v.1.8.3)).
