### ISSUE TITLE
Allow the specification of "custom" blockmodel

### ISSUE THREAD

**Issue by aleszib** [FATelarico/GUI-Generalised-Blockmodeling#4]
Allow the specification of "custom" blockmodel, similar as it is possible with Pajek if you select 
Network > Create Partition > Blockmodeling* > Random Start
And then select "User Fefined" instead of "Structural equivalence" as model specification.

**Comment by FATelarico** [comment]
At first I was not sure what this means exactly.

So, I went through Pajek's documentation and found out that 'the blockmodeling command seeks for the best partition of a given network satisfying given types of blocks' which can be either determined by the software or set manually by the user ([page 86](https://vlado.fmf.uni-lj.si/pub/networks/pajek/doc/pajekman.pdf#page=86)). 

Hence, I started working on a way to allow the user to input manually the type of block desired and this functionality is fully working in [version **1.6.0**](https://github.com/FATelarico/GUI-Generalised-Blockmodeling/releases/tag/v1.6.0):

- The blockmodeling side panel includes the option 'Pre-specify block-model'
- An additional side panel appears when the new box is checked which allows the user to :
    - use a personalised block-model by uploading an array contained in a `.RDS` or `.RData` file;
    - use a sample (which corresponds to the block-model used as an example in the package blockmodeling's help file (which is also linked directly);
    - employ a fully interactive table based on `handsontable.js`. However, this option is only available when the first two dimensions of the array equal 1 and convenient only for smaller block-models;
- Moreover, the user receives notifications informing of the advancement of the blockmodeling process, which can be quite useful when relatively complex models and/or networks are employed;
- Finally, when the user selects to pre-specify block-models, the number of clusters cannot be set (the option is hidden) and it is automatically determined based on the user-provided block-model.

**Comment by FATelarico** [comment]
With **[version 1.7.0](https://github.com/FATelarico/GUI-Generalised-Blockmodeling/releases/tag/v1.7.0)** the user has the ability to:
- select the size of a square block-model matrix
- build a personalised block model using visual aids (table)
- Build a personalised block model using dropdown block-type selection
- build a personalised block model in more steps thanks to the use of reactive values
- upload and edit pre-made block-model arrays with four dimensions
- override manual changes without having to reupload the file containing a personalised block-model

Possible developments include #6 giving the user the ability to download custom block-models created/modified using the app.
