### ISSUE TITLE
Not clear what is the format of the image matrix when it has more than 2 dimmensions.

### ISSUE THREAD

**Issue by aleszib** [FATelarico/GUI-Generalised-Blockmodeling#5]
The downloaded image matrix does not have a clear structure when it has more than two dimensions. Several options are possible here:
1. For now, just always drop the extra (one-length) dimensions .
2. Allow for downloading the results in different formats, one of which (perhaps the only one allowed if the extra dimensions are not dropped) is RDS R file (create the file for downloading with saveRDS function)
3. Add a note on how the text-file should be read in such case, perhaps also with a sample R code.

P.S.: The button should have the same label as the title "image matrix" instead of "matrix image".

**Comment by FATelarico** [comment]
In [version **1.6.0**](https://github.com/FATelarico/GUI-Generalised-Blockmodeling/releases/tag/v1.6.0), the user can download the selected image matrix as a text file only or a RDS file. When extra dimensions are not dropped, the app generates only RDS files.
