### ISSUE TITLE
Network Plot and Adjecentc matrix - problems when selecting partitioned matrix when no partition is available

### ISSUE THREAD

**Issue by aleszib** [FATelarico/GUI-Generalised-Blockmodeling#7]
If no partition is available (blockmodeling was not run yet), nothing is displayed. It would be better to either not even show this option in such case (no partition available) or to just ignore the selection (give the same plot as if "original" would be selected).

**Comment by FATelarico** [comment]
The new version returns the original matrix with the warning 'Plotting original matrix instead of partitioned because blockmodeling had not been ran yet' being showed for 20 seconds
