### ISSUE TITLE
Indicating network values (tie weights) with grayscale

### ISSUE THREAD

**Issue by aleszib** [FATelarico/GUI-Generalised-Blockmodeling#8]
Currently, if network is valued, at least with igraph it is possible to select that "Edges' width shows the network's values*". However, this often makes the network very had to read in case of denser networks. A better option is usually to use grayscale to indicate tie strenght (or some other color gradient), where white would indicate tie value 0 (these are of course not plotted) and black (or some other "strong" color) would indicate maximum tie value.

**Comment by FATelarico** [comment]
The enhancement is ready, but there are some bugs I intend to fix as of now when implementing it with visNetwork
